version: "3"
services:
  client:
    image: "keshav635/fibonexus-client"
    mem_limit: 128m
    hostname: client
    restart: always
  server:
    image: "keshav635/fibonexus-server"
    mem_limit: 128m
    hostname: api
    restart: always
    env_file:
      - ./server/.env
  worker:
    image: "keshav635/fibonexus-worker"
    mem_limit: 128m
    hostname: worker
    restart: always
    env_file:
      - ./worker/.env
  nginx:
    image: "keshav635/fibonexus-nginx"
    mem_limit: 128m
    hostname: nginx
    restart: always
    ports:
      - "80:80"