services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - ./postgres/.env

  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  api:
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app   
    env_file:
      - ./server/.env

  client:
    env_file:
      - ./client/.env
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    env_file:
      - ./worker/.env